### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by ethan-bmn** [victorfisac/Physac#54]
Whenever I use Physac, the CPU goes up to 40% (and when i'm not calling InitPhysics() it goes back to normal). Any fix for this?

**Comment by victorfisac** [comment]
@aganm Calling RunPhysicsStep from the main thread may drive into unexpected physics behaviours because of a lack of accuracy in the different motion deltas.

@ethan-bmn I guess there's some issue related to how is managed the thread loop in some way... or it should sleep at some points...

I have no time to work on this project because of my professional and personal stuff. Please, feel free to open new pull requests as it will contribute to all people starring this repository. 🙏

**Comment by victorfisac** [comment]
Fixed in https://github.com/victorfisac/Physac/commit/c4bf7fd702894abbf13800c8c09ae778b84c5cb4
